services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: servidor-clase-image
        container_name: servidor_clase
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html:delegated
            - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
            
    db:
        image: mysql:8.0
        container_name: servidor_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            # CAMBIO IMPORTANTE: Usamos un volumen interno de Docker
            - db_data:/var/lib/mysql 
            # AÃ‘ADIDO: Carpeta para pasar copias de seguridad a tu Google Drive
            - ./backups:/backups

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: servidor_pma
        links:
            - db:db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
            
# Esto crea el almacenamiento interno
volumes:
    db_data: